services:
  pat-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: kyrokrypt/pat-server:latest
    container_name: pat-server
    restart: unless-stopped
    environment:
      - MONGODB_URI=${MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: pat-mongodb
    restart: unless-stopped
    user: mongodb
    command:
      - mongod
      - --tlsMode
      - requireTLS
      - --tlsCertificateKeyFile
      - /etc/mongodb/mongodb.pem
      - --tlsCAFile
      - /etc/mongodb/ca.crt
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./certs:/etc/mongodb:ro

volumes:
  mongodb_data:
    name: pat-mongodb-data
  mongodb_config:
    name: pat-mongodb-config