services:
  server:
    build: .
    container_name: planner-and-tracker-server
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - MONGODB_URI=mongodb://mongodb:27017/planner-and-tracker
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

  mongodb:
    image: mongo:latest
    container_name: planner-and-tracker-mongodb
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: