name: Build and Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: production_environment
  cancel-in-progress: true

env:
  DOCKER_IMAGE: kyrokrypt/pat-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Create .env file
        run: |
          cat > .env << EOL
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          REFRESH_SECRET=${{ secrets.REFRESH_SECRET }}
          API_URL=${{ secrets.API_URL }}
          MONGO_PASS=${{ secrets.MONGO_PASS }}
          REDIS_PASS=${{ secrets.REDIS_PASS }}
          EOL
          
          # Debug: Show file contents (excluding sensitive values)
          cat .env | sed 's/=.*/=REDACTED/'

      - name: Create remote directory and copy files
        env:
          SSH_CONNECTION: ${{ secrets.SSH_CONNECTION }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_CONNECTION "mkdir -p ~/pat-server"
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no docker-compose.yml $SSH_CONNECTION:~/pat-server/
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no .env $SSH_CONNECTION:~/pat-server/
          sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no nginx.conf $SSH_CONNECTION:~/pat-server/

          # Debug: Verify file transfer and contents
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_CONNECTION "cd ~/pat-server && ls -la && cat .env | sed 's/=.*/=REDACTED/'"

      - name: Deploy to VPS
        env:
          SSH_CONNECTION: ${{ secrets.SSH_CONNECTION }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_CONNECTION "cd ~/pat-server && \
          docker compose down && \
          docker compose pull && \
          docker compose up -d && \
          docker compose logs"