name: Deploy PAT Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_IMAGE: kyrokrypt/pat-server

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:latest

      - name: Install Cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: Deploy via Cloudflared
        env:
          CLOUDFLARED_TOKEN: ${{ secrets.CLOUDFLARED_TOKEN }}
        run: |
          # Authenticate with Cloudflared
          echo "$CLOUDFLARED_TOKEN" > ~/.cloudflared/cert.json
          
          # Run deployment commands through Cloudflared
          cloudflared access ssh --hostname <your-tunnel-hostname> -- powershell -Command "
            Set-Location C:\Users\timothy\Desktop\pat-server
            docker-compose pull pat-server
            docker-compose up -d --force-recreate pat-server
            docker image prune -f
          "